### ISSUE TITLE
SyntaxError: : unexpected character after line continuation character

### ISSUE THREAD

**Issue by midiisc** [MathItYT/manim-studio#16] opened 2023-12-20 05:02 UTC
**Describe the bug**
I downloaded the latest release 0.6.6 and tried running it. The error is 
File "/home/ddd/anaconda3/envs/manim/lib/python3.11/site-packages/manim_studio/mobject_picker.py", line 311
    f"setattr(self, {name.__repr__()}, MathTex({f"\\ln x=\\int_1^x{dt\\over t}".__repr__()}))")
SyntaxError: unexpected character after line continuation character"

**To Reproduce**
1. Install manim-studio using pip3 inside conda environment
2. Run manim-studio

**Expected behavior**
I was expecting the GUI to openup

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.10.1
 - Browser: Chrome
 - Version  120

**Smartphone (please complete the following information):**
NA

**Additional context**
Nil

**Comment by MathItYT** [comment] 2023-12-20 13:48
Hi! I'm aware of this. The problem comes from an incompatibility with new features from Python 3.12. A solution could be installing Python 3.12 in Ubuntu. **Never delete your original Python installation! You must only install the new version, keeping the current one.** Open a terminal and run these commands in order:
`sudo add-apt-repository ppa:deadsnakes/ppa`
`sudo apt update`
`sudo apt install python3.12`
Then, uninstall Manim Studio from your older environment and install `virtualenv` with `pip3.12 install virtualenv`.
Go to your workspace folder and create a new virtualenv with:
`python3.12 -m virtualenv .venv`
After that, run in the same folder:
`source .venv/bin/activate`
Finally, with the environment activated, run:
`pip3.12 install manim-studio`
And run `manim-studio` in that environment.

Tell me what's going on now :)

**Comment by midiisc** [comment] 2023-12-20 17:38
I tried but we have new error.


qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland, xcb, wayland-egl, vnc, offscreen, linuxfb, minimalegl, eglfs, vkkhrdisplay, minimal.

Aborted (core dumped)

**Comment by MathItYT** [comment] 2023-12-20 17:51
This is mostly caused by having two differents versions of PyQt6 and PyQt6-Qt6. Try doing `pip install -U --force-reinstall PyQt6==6.6.0` and `pip install -U --force-reinstall PyQt6-Qt6==6.6.0`

**Comment by midiisc** [comment] 2023-12-21 03:13
That didn't work. What finally did was 
sudo apt install libxcb-cursor0

Btw, I didn't install Python 3.12 globally, but inside Conda environment which is what I was using. Still worked. Is this fine?

**Comment by MathItYT** [comment] 2023-12-21 03:17
If that worked, it should be fine.

**Comment by midiisc** [comment] 2023-12-21 03:21
Thank you

**Comment by MathItYT** [comment] 2023-12-21 03:24
I'll close this issue. If you encounter another bug, please open an issue :)

**Closed** 2023-12-21 03:24 UTC
